spring.application.name=siw-site
#==================================
# = Datasource
#==================================
# Configurazione JPA/Hibernate
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/festival
spring.datasource.username=postgres
spring.datasource.password=Redbull24*
spring.jpa.properties.hibernate.format_sql=true
#==================================
# = Web server
#==================================
server.port=8080
#==================================
# = Thymeleaf configurations
#==================================
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false
#true in true di deploy
spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=UTF-8
#==================================
# = OAuth2 Google
#==================================
#spring.security.oauth2.client.registration.google.client-id=185290317815-ilrhfgqhqja5rrjclctlsjnqd9qq6an4.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.scope=email,profile
#spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
#spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
#spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
#spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
#spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
