# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: siw-site
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/festival
    username: postgres
    password: Redbull24*
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    cache: false
    enabled: true
    encoding: UTF-8
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
server:
  port: 8080
