/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnershipRouteImport } from './routes/partnership'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfiloRouteImport } from './routes/profilo'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as FestivalIndexRouteImport } from './routes/festival.index'
import { Route as FestivalIdRouteImport } from './routes/festival.$id'
import { Route as FilmIndexRouteImport } from './routes/film.index'
import { Route as FilmIdRouteImport } from './routes/film.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfiloRoute = ProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalIndexRoute = FestivalIndexRouteImport.update({
  id: '/festival/',
  path: '/festival/',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalIdRoute = FestivalIdRouteImport.update({
  id: '/festival/$id',
  path: '/festival/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmIndexRoute = FilmIndexRouteImport.update({
  id: '/film/',
  path: '/film/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmIdRoute = FilmIdRouteImport.update({
  id: '/film/$id',
  path: '/film/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/login': typeof LoginRoute
  '/partnership': typeof PartnershipRoute
  '/privacy': typeof PrivacyRoute
  '/profilo': typeof ProfiloRoute
  '/register': typeof RegisterRoute
  '/festival/$id': typeof FestivalIdRoute
  '/film/$id': typeof FilmIdRoute
  '/festival/': typeof FestivalIndexRoute
  '/film/': typeof FilmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/login': typeof LoginRoute
  '/partnership': typeof PartnershipRoute
  '/privacy': typeof PrivacyRoute
  '/profilo': typeof ProfiloRoute
  '/register': typeof RegisterRoute
  '/festival/$id': typeof FestivalIdRoute
  '/film/$id': typeof FilmIdRoute
  '/festival': typeof FestivalIndexRoute
  '/film': typeof FilmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/login': typeof LoginRoute
  '/partnership': typeof PartnershipRoute
  '/privacy': typeof PrivacyRoute
  '/profilo': typeof ProfiloRoute
  '/register': typeof RegisterRoute
  '/festival/$id': typeof FestivalIdRoute
  '/film/$id': typeof FilmIdRoute
  '/festival/': typeof FestivalIndexRoute
  '/film/': typeof FilmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chi-siamo'
    | '/contatti'
    | '/login'
    | '/partnership'
    | '/privacy'
    | '/profilo'
    | '/register'
    | '/festival/$id'
    | '/film/$id'
    | '/festival/'
    | '/film/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chi-siamo'
    | '/contatti'
    | '/login'
    | '/partnership'
    | '/privacy'
    | '/profilo'
    | '/register'
    | '/festival/$id'
    | '/film/$id'
    | '/festival'
    | '/film'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chi-siamo'
    | '/contatti'
    | '/login'
    | '/partnership'
    | '/privacy'
    | '/profilo'
    | '/register'
    | '/festival/$id'
    | '/film/$id'
    | '/festival/'
    | '/film/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  LoginRoute: typeof LoginRoute
  PartnershipRoute: typeof PartnershipRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfiloRoute: typeof ProfiloRoute
  RegisterRoute: typeof RegisterRoute
  FestivalIdRoute: typeof FestivalIdRoute
  FilmIdRoute: typeof FilmIdRoute
  FestivalIndexRoute: typeof FestivalIndexRoute
  FilmIndexRoute: typeof FilmIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership': {
      id: '/partnership'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profilo': {
      id: '/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof ProfiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival/': {
      id: '/festival/'
      path: '/festival'
      fullPath: '/festival/'
      preLoaderRoute: typeof FestivalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival/$id': {
      id: '/festival/$id'
      path: '/festival/$id'
      fullPath: '/festival/$id'
      preLoaderRoute: typeof FestivalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/': {
      id: '/film/'
      path: '/film'
      fullPath: '/film/'
      preLoaderRoute: typeof FilmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$id': {
      id: '/film/$id'
      path: '/film/$id'
      fullPath: '/film/$id'
      preLoaderRoute: typeof FilmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  LoginRoute: LoginRoute,
  PartnershipRoute: PartnershipRoute,
  PrivacyRoute: PrivacyRoute,
  ProfiloRoute: ProfiloRoute,
  RegisterRoute: RegisterRoute,
  FestivalIdRoute: FestivalIdRoute,
  FilmIdRoute: FilmIdRoute,
  FestivalIndexRoute: FestivalIndexRoute,
  FilmIndexRoute: FilmIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
